GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9uaEBtYWlsLmNvbSIsImlhdCI6MTcwMzg3NzYxMSwiZXhwIjoxNzAzODc3NjMxfQ.2gTPQpd5ProLDYnfXWyfAaJic0rKZpBz1FEA7hxpyLA

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Funn",
    "email": "fun@mail.com",
    "password": "123456",
    "confirmPassword": "123456"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "jonh@mail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token


###
DELETE http://localhost:5000/logout